// web/src/pages/demo/editor/index.tsx
import React, { useState } from 'react';
import { Card, Typography } from 'antd';

import { PageContainer } from '@/components';
import RichEditor from '@/components/RichEditor';

/**
 * 编辑器示例页面
 */
const EditorDemoPage: React.FC = () => {
  const [html, setHtml] = useState<string>('<p>这是一个示例内容</p>');

  return (
    <PageContainer>
      <Card style={{ background: '#fff' }}>
        <Typography.Title level={4} style={{ marginTop: 0 }}>
          富文本编辑器示例
        </Typography.Title>
        <Typography.Paragraph type="secondary">
          演示 RichEditor 的基本用法：受控 value + onChange，并支持图片/视频上传。
        </Typography.Paragraph>

        <RichEditor value={html} onChange={setHtml} />

        <div style={{ marginTop: 16 }}>
          <Typography.Title level={5}>当前 HTML</Typography.Title>
          <pre
            style={{
              background: '#fafafa',
              border: '1px solid #f0f0f0',
              borderRadius: 6,
              padding: 12,
              whiteSpace: 'pre-wrap',
              wordBreak: 'break-word',
            }}
          >
            {html}
          </pre>
        </div>
      </Card>
    </PageContainer>
  );
};

export default EditorDemoPage;

// web/src/views/demo/editor/index.vue
<template>
  <div class="art-full-height">
    <ElCard shadow="never" class="art-card">
      <template #header>
        <div class="flex flex-col gap-1">
          <span class="text-lg font-medium">富文本编辑器示例</span>
          <span class="text-sm text-g-500">演示 RichEditor 的基本用法：受控 value + onChange，并支持图片/视频上传。</span>
        </div>
      </template>

      <div class="mb-6">
        <ArtWangEditor v-model="html" height="400px" />
      </div>

      <div class="mt-6">
        <div class="text-base font-medium mb-3">当前 HTML 内容</div>
        <div class="p-4 bg-g-100 rounded-md border border-g-200 overflow-auto">
          <pre class="text-sm text-g-700 whitespace-pre-wrap break-all">{{ html }}</pre>
        </div>
      </div>
    </ElCard>
  </div>
</template>

<script setup lang="ts">
  import { ref } from 'vue'
  import ArtWangEditor from '@/components/core/forms/art-wang-editor/index.vue'

  defineOptions({ name: 'DemoEditor' })

  const html = ref('<p>这是一个示例内容</p>')
</script>
